### ISSUE TITLE
macos: Duplicate symbols

### ISSUE THREAD

**Issue by skull-squadron** [mesalock-linux/mesalink#14] opened 2018-07-01 02:09 UTC
It looks like the duplication of LLVM compiler intrinsics. 30% chance that it's because autotooling assumes `/usr/bin/gcc` is GCC, when it's Apple's version of Clang/LLVM.
 
### Environment

- macOS 10.13.5
- Xcode/CLT 9.4.1
- Latest rust nightly - 1.28.0-nightly (e2348c2db 2018-06-07)
- mesalink latest stable or master
- Homebrew packages installed
  - rustup 1.11.0
  - autoconf 2.69
  - automake 1.16.1
  - libtool 2.4.6
  - coreutils 8.29
  - grep 3.1
  - gawk 4.2.1

### C compiler

```
$ gcc --version # autogen's choice is gcc
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

### Build command

      curl -fsL https://github.com/mesalock-linux/mesalink/archive/master.tar.gz | tar zx && \
      (cd mesalink-master && ./autogen.sh && make -j); \
      rm -rf mesalink-master/

### Build output

```
*** WARNING: I am going to run 'configure' with no arguments.
*** If you wish to pass any to it, please specify them on the
*** './autogen.sh' command line.

configure.ac:69: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:197: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2598: _AC_COMPILE_IFELSE is expanded from...
../../lib/autoconf/general.m4:2608: AC_COMPILE_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:643: AS_IF is expanded from...
../../lib/autoconf/general.m4:2046: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2059: AC_CACHE_CHECK is expanded from...
/usr/local/share/aclocal/ax_check_compile_flag.m4:74: AX_CHECK_COMPILE_FLAG is expanded from...
/usr/local/share/aclocal/ax_append_compile_flags.m4:67: AX_APPEND_COMPILE_FLAGS is expanded from...
m4/ax_harden_compiler_flags.m4:160: AX_HARDEN_CC_COMPILER_FLAGS is expanded from...
configure.ac:69: the top level
aclocal: overwriting 'm4/ax_append_compile_flags.m4' with '/usr/local/share/aclocal/ax_append_compile_flags.m4'
aclocal: overwriting 'm4/ax_append_flag.m4' with '/usr/local/share/aclocal/ax_append_flag.m4'
aclocal: overwriting 'm4/ax_check_compile_flag.m4' with '/usr/local/share/aclocal/ax_check_compile_flag.m4'
aclocal: overwriting 'm4/ax_check_link_flag.m4' with '/usr/local/share/aclocal/ax_check_link_flag.m4'
aclocal: overwriting 'm4/ax_compiler_vendor.m4' with '/usr/local/share/aclocal/ax_compiler_vendor.m4'
aclocal: installing 'm4/ax_require_defined.m4' from '/usr/local/share/aclocal/ax_require_defined.m4'
aclocal: installing 'm4/libtool.m4' from '/usr/local/share/aclocal/libtool.m4'
aclocal: installing 'm4/ltoptions.m4' from '/usr/local/share/aclocal/ltoptions.m4'
aclocal: installing 'm4/ltsugar.m4' from '/usr/local/share/aclocal/ltsugar.m4'
aclocal: installing 'm4/ltversion.m4' from '/usr/local/share/aclocal/ltversion.m4'
aclocal: installing 'm4/lt~obsolete.m4' from '/usr/local/share/aclocal/lt~obsolete.m4'
configure.ac:69: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:197: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2598: _AC_COMPILE_IFELSE is expanded from...
../../lib/autoconf/general.m4:2608: AC_COMPILE_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:643: AS_IF is expanded from...
../../lib/autoconf/general.m4:2046: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2059: AC_CACHE_CHECK is expanded from...
m4/ax_check_compile_flag.m4:74: AX_CHECK_COMPILE_FLAG is expanded from...
m4/ax_append_compile_flags.m4:67: AX_APPEND_COMPILE_FLAGS is expanded from...
m4/ax_harden_compiler_flags.m4:160: AX_HARDEN_CC_COMPILER_FLAGS is expanded from...
configure.ac:69: the top level
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
configure.ac:69: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:197: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2598: _AC_COMPILE_IFELSE is expanded from...
../../lib/autoconf/general.m4:2608: AC_COMPILE_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:643: AS_IF is expanded from...
../../lib/autoconf/general.m4:2046: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2059: AC_CACHE_CHECK is expanded from...
m4/ax_check_compile_flag.m4:74: AX_CHECK_COMPILE_FLAG is expanded from...
m4/ax_append_compile_flags.m4:67: AX_APPEND_COMPILE_FLAGS is expanded from...
m4/ax_harden_compiler_flags.m4:160: AX_HARDEN_CC_COMPILER_FLAGS is expanded from...
configure.ac:69: the top level
configure.ac:69: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:197: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2598: _AC_COMPILE_IFELSE is expanded from...
../../lib/autoconf/general.m4:2608: AC_COMPILE_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:643: AS_IF is expanded from...
../../lib/autoconf/general.m4:2046: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2059: AC_CACHE_CHECK is expanded from...
m4/ax_check_compile_flag.m4:74: AX_CHECK_COMPILE_FLAG is expanded from...
m4/ax_append_compile_flags.m4:67: AX_APPEND_COMPILE_FLAGS is expanded from...
m4/ax_harden_compiler_flags.m4:160: AX_HARDEN_CC_COMPILER_FLAGS is expanded from...
configure.ac:69: the top level
autoreconf: configure.ac: tracing
configure.ac:69: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:197: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2598: _AC_COMPILE_IFELSE is expanded from...
../../lib/autoconf/general.m4:2608: AC_COMPILE_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:643: AS_IF is expanded from...
../../lib/autoconf/general.m4:2046: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2059: AC_CACHE_CHECK is expanded from...
m4/ax_check_compile_flag.m4:74: AX_CHECK_COMPILE_FLAG is expanded from...
m4/ax_append_compile_flags.m4:67: AX_APPEND_COMPILE_FLAGS is expanded from...
m4/ax_harden_compiler_flags.m4:160: AX_HARDEN_CC_COMPILER_FLAGS is expanded from...
configure.ac:69: the top level
autoreconf: configure.ac: creating directory build-aux
autoreconf: running: glibtoolize --copy --force
glibtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
glibtoolize: copying file 'build-aux/ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: copying file 'm4/libtool.m4'
glibtoolize: copying file 'm4/ltoptions.m4'
glibtoolize: copying file 'm4/ltsugar.m4'
glibtoolize: copying file 'm4/ltversion.m4'
glibtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:69: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:197: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2598: _AC_COMPILE_IFELSE is expanded from...
../../lib/autoconf/general.m4:2608: AC_COMPILE_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:643: AS_IF is expanded from...
../../lib/autoconf/general.m4:2046: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2059: AC_CACHE_CHECK is expanded from...
m4/ax_check_compile_flag.m4:74: AX_CHECK_COMPILE_FLAG is expanded from...
m4/ax_append_compile_flags.m4:67: AX_APPEND_COMPILE_FLAGS is expanded from...
m4/ax_harden_compiler_flags.m4:160: AX_HARDEN_CC_COMPILER_FLAGS is expanded from...
configure.ac:69: the top level
configure.ac:69: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:197: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2598: _AC_COMPILE_IFELSE is expanded from...
../../lib/autoconf/general.m4:2608: AC_COMPILE_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:643: AS_IF is expanded from...
../../lib/autoconf/general.m4:2046: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2059: AC_CACHE_CHECK is expanded from...
m4/ax_check_compile_flag.m4:74: AX_CHECK_COMPILE_FLAG is expanded from...
m4/ax_append_compile_flags.m4:67: AX_APPEND_COMPILE_FLAGS is expanded from...
m4/ax_harden_compiler_flags.m4:160: AX_HARDEN_CC_COMPILER_FLAGS is expanded from...
configure.ac:69: the top level
autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoconf --force
configure.ac:69: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:197: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2598: _AC_COMPILE_IFELSE is expanded from...
../../lib/autoconf/general.m4:2608: AC_COMPILE_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:643: AS_IF is expanded from...
../../lib/autoconf/general.m4:2046: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2059: AC_CACHE_CHECK is expanded from...
m4/ax_check_compile_flag.m4:74: AX_CHECK_COMPILE_FLAG is expanded from...
m4/ax_append_compile_flags.m4:67: AX_APPEND_COMPILE_FLAGS is expanded from...
m4/ax_harden_compiler_flags.m4:160: AX_HARDEN_CC_COMPILER_FLAGS is expanded from...
configure.ac:69: the top level
autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoheader --force
configure.ac:69: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:197: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2598: _AC_COMPILE_IFELSE is expanded from...
../../lib/autoconf/general.m4:2608: AC_COMPILE_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:643: AS_IF is expanded from...
../../lib/autoconf/general.m4:2046: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2059: AC_CACHE_CHECK is expanded from...
m4/ax_check_compile_flag.m4:74: AX_CHECK_COMPILE_FLAG is expanded from...
m4/ax_append_compile_flags.m4:67: AX_APPEND_COMPILE_FLAGS is expanded from...
m4/ax_harden_compiler_flags.m4:160: AX_HARDEN_CC_COMPILER_FLAGS is expanded from...
configure.ac:69: the top level
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:69: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:197: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2598: _AC_COMPILE_IFELSE is expanded from...
../../lib/autoconf/general.m4:2608: AC_COMPILE_IFELSE is expanded from...
../../lib/m4sugar/m4sh.m4:643: AS_IF is expanded from...
../../lib/autoconf/general.m4:2046: AC_CACHE_VAL is expanded from...
../../lib/autoconf/general.m4:2059: AC_CACHE_CHECK is expanded from...
m4/ax_check_compile_flag.m4:74: AX_CHECK_COMPILE_FLAG is expanded from...
m4/ax_append_compile_flags.m4:67: AX_APPEND_COMPILE_FLAGS is expanded from...
m4/ax_harden_compiler_flags.m4:160: AX_HARDEN_CC_COMPILER_FLAGS is expanded from...
configure.ac:69: the top level
configure.ac:21: installing 'build-aux/ar-lib'
configure.ac:18: installing 'build-aux/compile'
configure.ac:8: installing 'build-aux/config.guess'
configure.ac:8: installing 'build-aux/config.sub'
configure.ac:12: installing 'build-aux/install-sh'
configure.ac:12: installing 'build-aux/missing'
autoreconf: Leaving directory `.'
checking build system type... x86_64-apple-darwin17.6.0
checking host system type... x86_64-apple-darwin17.6.0
checking for a BSD-compatible install... /usr/local/bin/ginstall -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/local/bin/gmkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether gcc and cc understand -c and -o together... yes
checking for ar... ar
checking the archiver (ar) interface... ar
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/local/bin/gsed
checking for grep that handles long lines and -e... /usr/local/bin/ggrep
checking for egrep... /usr/local/bin/ggrep -E
checking for fgrep... /usr/local/bin/ggrep -F
checking for ld used by gcc... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking how to convert x86_64-apple-darwin17.6.0 file names to x86_64-apple-darwin17.6.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin17.6.0 file names to toolchain format... func_convert_file_noop
checking for /Library/Developer/CommandLineTools/usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin17.6.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking for string.h... (cached) yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking for unistd.h... (cached) yes
checking for gethostbyname... yes
checking for memset... yes
checking for socket... yes
checking for cargo... yes
checking for rustc... yes
checking for C compiler vendor... clang
checking whether the linker accepts ... yes
checking for vcs system... none
checking for vcs checkout... no
checking for debug... no
checking whether the linker accepts -Werror... yes
checking whether the linker accepts -z relro -z now... no
checking whether the linker accepts -pie... no
checking whether C compiler accepts -Werror... yes
checking whether C compiler accepts -Wno-pragmas... yes
checking whether C compiler accepts -Wall... yes
checking whether C compiler accepts -Wno-strict-aliasing... no
checking whether C compiler accepts -Wextra... yes
checking whether C compiler accepts -Wunknown-pragmas... yes
checking whether C compiler accepts -Wthis-test-should-fail... no
checking whether C compiler accepts --param=ssp-buffer-size=1... yes
checking whether C compiler accepts -Waddress... yes
checking whether C compiler accepts -Warray-bounds... yes
checking whether C compiler accepts -Wbad-function-cast... yes
checking whether C compiler accepts -Wchar-subscripts... yes
checking whether C compiler accepts -Wcomment... yes
checking whether C compiler accepts -Wfloat-equal... yes
checking whether C compiler accepts -Wformat-security... yes
checking whether C compiler accepts -Wformat=2... yes
checking whether C compiler accepts -Wmaybe-uninitialized... no
checking whether C compiler accepts -Wmissing-field-initializers... yes
checking whether C compiler accepts -Wmissing-noreturn... yes
checking whether C compiler accepts -Wmissing-prototypes... yes
checking whether C compiler accepts -Wnested-externs... yes
checking whether C compiler accepts -Wnormalized=id... no
checking whether C compiler accepts -Woverride-init... no
checking whether C compiler accepts -Wpointer-arith... yes
checking whether C compiler accepts -Wpointer-sign... yes
checking whether C compiler accepts -Wredundant-decls... yes
checking whether C compiler accepts -Wshadow... yes
checking whether C compiler accepts -Wshorten-64-to-32... yes
checking whether C compiler accepts -Wsign-compare... yes
checking whether C compiler accepts -Wstrict-overflow=1... yes
checking whether C compiler accepts -Wstrict-prototypes... yes
checking whether C compiler accepts -Wswitch-enum... yes
checking whether C compiler accepts -Wundef... yes
checking whether C compiler accepts -Wunused... yes
checking whether C compiler accepts -Wunused-result... yes
checking whether C compiler accepts -Wunused-variable... yes
checking whether C compiler accepts -Wwrite-strings... yes
checking whether C compiler accepts -fwrapv... yes
checking whether the linker accepts -Werror... (cached) yes
checking whether the linker accepts -z relro -z now... (cached) no
checking whether the linker accepts -pie... (cached) no
checking for debug... no
creating mesalink-config - generic 0.6.0 for -lmesalink
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating mesalink/options.h
config.status: creating mesalink/version.h
config.status: creating config.h
config.status: executing libtool commands
---
Running make clean ...

---
Configuration summary for mesalink version 0.6.0

   * Installation prefix:        /usr/local
   * Host:                       x86_64-apple-darwin17.6.0
   * Rust Host:                  
   * C Compiler:                 gcc
   * C Compiler vendor:          clang
   * C Flags:                    -Os -fvisibility=hidden -ffunction-sections -fdata-sections  -Wno-pragmas -Wall -Wextra -Wunknown-pragmas --param=ssp-buffer-size=1 -Waddress -Warray-bounds -Wbad-function-cast -Wchar-subscripts -Wcomment -Wfloat-equal -Wformat-security -Wformat=2 -Wmissing-field-initializers -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wpointer-sign -Wredundant-decls -Wshadow -Wshorten-64-to-32 -Wsign-compare -Wstrict-overflow=1 -Wstrict-prototypes -Wswitch-enum -Wundef -Wunused -Wunused-result -Wunused-variable -Wwrite-strings -fwrapv
   * Debug enabled:              no
   * Nightly Rust:               yes
   * Examples:                   no

   Features 
   * Logging and error strings:  yes
   * AES-GCM:                    yes
   * Chacha20-Poly1305:          yes
   * TLS 1.3 (draft):            yes
   * X25519 key exchange:        yes
   * EC key exchange:            yes
   * RSA signature verification: yes
   * EC signature verification:  yes

---
/Library/Developer/CommandLineTools/usr/bin/make  all-am
cd . && \
	 cargo rustc \
		--release --no-default-features --features " client_apis server_apis error_strings aesgcm chachapoly tls13 x25519 ecdh ecdsa verifier"  -- -C overflow-checks=yes -C link-args=-Wl,-dead_strip -C opt-level=z
    Updating git repository `https://github.com/mesalock-linux/rustls`
    Updating git repository `https://github.com/mesalock-linux/sct.rs`
    Updating git repository `https://github.com/kevinis/enum_to_str_derive.git`
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling cc v1.0.17
   Compiling untrusted v0.6.2
   Compiling unicode-xid v0.0.4
   Compiling quote v0.3.15
   Compiling safemem v0.2.0
   Compiling byteorder v1.2.3
   Compiling cfg-if v0.1.4
   Compiling mesalink v0.6.0 (file:///private/tmp/mesalink-master)
   Compiling lazy_static v1.0.1
   Compiling libc v0.2.42
   Compiling synom v0.11.3
   Compiling log v0.4.3
   Compiling base64 v0.9.2
   Compiling syn v0.11.11
   Compiling ring v0.13.0-alpha5
   Compiling enum_to_str_derive v0.1.0 (https://github.com/kevinis/enum_to_str_derive.git#35a1c87b)
   Compiling sct v0.3.0 (https://github.com/mesalock-linux/sct.rs?branch=mesalink#3d77a2ab)
   Compiling webpki v0.18.0-alpha4
   Compiling webpki-roots v0.14.0
   Compiling rustls v0.12.0 (https://github.com/mesalock-linux/rustls?branch=mesalink#82e2136e)
    Finished release [optimized] target(s) in 1m 35s
/bin/sh ./libtool  --tag=CC   --mode=link gcc  -Os -fvisibility=hidden -ffunction-sections -fdata-sections  -Wno-pragmas -Wall -Wextra -Wunknown-pragmas --param=ssp-buffer-size=1 -Waddress -Warray-bounds -Wbad-function-cast -Wchar-subscripts -Wcomment -Wfloat-equal -Wformat-security -Wformat=2 -Wmissing-field-initializers -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wpointer-sign -Wredundant-decls -Wshadow -Wshorten-64-to-32 -Wsign-compare -Wstrict-overflow=1 -Wstrict-prototypes -Wswitch-enum -Wundef -Wunused -Wunused-result -Wunused-variable -Wwrite-strings -fwrapv -export-dynamic -no-undefined -version-info 6:0:0 -export-symbols-regex "^mesalink_.*"   -o libmesalink.la -rpath /usr/local/lib  /tmp/mesalink-master/target/release/libmesalink_internals.la 
libtool: link: /usr/bin/nm -B   /tmp/mesalink-master/target/release/.libs/libmesalink_internals.a | sed -n -e 's/^.*[	 ]\([BCDEGRST][BCDEGRST]*\)[	 ][	 ]*_\([_A-Za-z][_A-Za-z0-9]*\)$/\1 _\2 \2/p' | sed '/ __gnu_lto/d' | /usr/local/bin/gsed 's/.* //' | sort | uniq > .libs/libmesalink.exp
libtool: link: /usr/local/bin/ggrep -E -e "^mesalink_.*" ".libs/libmesalink.exp" > ".libs/libmesalink.expT"
libtool: link: mv -f ".libs/libmesalink.expT" ".libs/libmesalink.exp"
libtool: link: sed 's|^|_|' < .libs/libmesalink.exp > .libs/libmesalink-symbols.expsym
libtool: link: gcc -dynamiclib  -o .libs/libmesalink.6.dylib   -Wl,-force_load,/tmp/mesalink-master/target/release/.libs/libmesalink_internals.a   -Os   -lm -ldl -lresolv -framework Security -install_name  /usr/local/lib/libmesalink.6.dylib -compatibility_version 7 -current_version 7.0 -Wl,-single_module -Wl,-exported_symbols_list,.libs/libmesalink-symbols.expsym
duplicate symbol ___floatdisf in:
    /tmp/mesalink-master/target/release/.libs/libmesalink_internals.a(compiler_builtins-082e7faacb91b99b.compiler_builtins0-4d50cb6996581a3196f5470ee396f32f.rs.rcgu.o)
    /tmp/mesalink-master/target/release/.libs/libmesalink_internals.a(floatdisf.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libmesalink.la] Error 1
make: *** [all] Error 2
```

**Comment by ymjing** [comment] 2018-08-09 04:01
Finally we found the problem. The duplicate symbol `___floatdisf`  is caused by a bug in rust compiler builtins. We submitted [PR #252](https://github.com/rust-lang-nursery/compiler-builtins/pull/252) and now the fix is merged. 

Before the fix gets its way into stable Rust, we add a temporary workaround is to remove the duplicate `floatdisf.o` from `libmesalink_internals.a`, which is done by `ar`. See Line 9 in `src/include.mk`. The workaround works for both stable and nightly Rust, including stable Rust prior to 1.28.0.

**Closed as completed by ymjing** 2018-08-09 04:01 UTC
